In [1]:
import pandas as pd
df3=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]
df3

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [2]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    object
 1   Security               503 non-null    object
 2   GICS Sector            503 non-null    object
 3   GICS Sub-Industry      503 non-null    object
 4   Headquarters Location  503 non-null    object
 5   Date added             503 non-null    object
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    object
dtypes: int64(1), object(7)
memory usage: 31.6+ KB

In [5]:
df3['Date added']=pd.to_datetime(df3['Date added'])
df3.info()
df3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    object
 1   Security               503 non-null    object
 2   GICS Sector            503 non-null    object
 3   GICS Sub-Industry      503 non-null    object
 4   Headquarters Location  503 non-null    object
 5   Date added             503 non-null    datetime64[ns]
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 31.6+ KB

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [6]:
df3['new']=df3['Date added'].dt.year
df3

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,new
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,1957
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,2017
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,1957
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),2012
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,2011
...,...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,2019
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,2001
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,2013

In [9]:
l1=[]
for i  in df3['Date added']:
    l1.append(i.year)
print(l1)
df3['new2']=l1
df3

[1957, 2017, 1957, 2012, 2011, 1997, 2017, 1998, 1999, 2000, 1985, 2023, 2007, 2016, 2017, 2017, 2013, 2016, 1995, 2014, 2006, 1957, 2005, 2019, 1991, 1957, 1976, 1980, 2007, 2016, 2005, 2013, 1992, 2008, 1999, 2017, 1996, 1997, 2024, 1982, 1995, 2012, 2022, 1957, 2018, 2016, 2007, 1983, 2019, 1989, 1981, 1997, 2007, 1987, 2023, 2017, 1984, 1976, 1972, 1972, 2010, 1999, 2021, 2003, 2011, 2023, 1995, 1957, 2009, 1995, 1957, 2014, 2018, 2021, 1982, 2023, 2023, 2006, 2007, 2017, 2021, 2022, 1957, 1998, 1997, 2010, 1998, 2020, 1957, 2017, 2006, 2019, 2001, 2016, 1985, 2008, 2021, 1997, 2016, 1957, 2011, 2010, 2015, 1976, 1997, 2001, 1993, 1988, 2016, 1969, 2006, 1957, 1957, 2006, 1957, 2002, 1983, 1957, 1957, 2005, 2022, 2016, 2018, 1995, 2018, 2019, 2022, 1993, 2008, 2024, 2012, 1957, 1965, 1957, 1998, 1995, 2008, 2021, 2024, 1957, 2024, 2013, 2000, 2020, 2018, 2016, 2007, 2012, 2011, 2016, 2020, 2025, 1985, 2019, 2005, 1957, 1976, 2019, 1994, 1957, 2002, 1989, 1957, 2011, 2002, 2002, 1965, 2021, 1957, 2000, 2021, 2022, 1997, 2015, 2001, 2024, 2014, 2006, 2017, 2018, 2009, 1957, 2025, 2007, 2007, 2016, 1957, 2010, 2021, 2023, 2008, 2016, 1980, 2006, 1996, 2022, 1997, 2001, 1957, 2018, 2016, 2019, 2019, 1998, 2011, 2012, 2017, 1957, 2023, 2024, 2003, 2021, 1957, 1957, 2013, 1973, 2004, 2016, 1989, 2024, 2002, 1957, 1957, 1984, 2015, 2008, 2015, 1957, 1984, 2015, 2017, 2016, 1988, 1957, 2009, 2007, 2016, 1974, 2023, 2012, 1997, 2018, 1957, 2019, 2017, 1986, 2017, 2020, 2023, 1976, 2007, 1976, 1957, 1992, 2000, 2008, 2008, 2022, 2017, 2009, 2015, 2023, 2018, 2007, 1973, 2010, 1975, 2006, 1989, 2023, 2022, 1994, 2018, 1957, 2006, 2012, 2024, 1997, 2015, 1957, 2008, 2004, 2012, 2018, 2019, 2019, 2005, 2024, 1970, 1992, 2019, 2016, 1957, 1995, 1984, 2023, 2012, 2004, 2011, 2019, 1998, 1987, 2014, 1981, 2008, 2021, 2003, 1970, 1999, 1986, 1957, 2013, 2000, 2016, 2017, 2007, 1994, 1994, 2016, 2021, 2013, 2022, 1976, 2012, 2021, 2012, 1998, 1993, 2011, 1957, 2018, 2008, 1999, 2010, 1969, 2013, 2015, 1976, 1988, 2000, 2022, 1957, 1998, 1957, 2017, 2010, 1985, 2001, 2019, 2021, 2009, 1957, 2019, 1997, 2022, 2010, 1989, 2020, 1980, 2017, 2024, 2023, 1994, 1985, 1998, 2020, 2015, 2012, 1957, 1957, 2022, 2008, 2012, 1999, 1988, 2020, 1957, 2001, 2002, 1957, 1997, 2003, 2002, 1957, 2021, 2005, 1984, 2009, 1999, 2002, 2007, 2017, 1957, 2015, 2017, 2013, 1998, 2008, 2017, 1985, 2000, 2018, 2009, 2009, 2014, 1957, 2008, 2017, 1957, 2012, 2017, 2019, 1964, 2002, 2015, 2008, 2024, 1982, 2024, 1957, 1994, 1982, 2000, 2003, 2022, 2019, 2000, 2024, 2015, 2017, 1986, 2019, 2019, 2018, 2004, 2022, 1976, 2011, 2020, 2020, 2020, 2001, 2024, 1978, 2004, 1985, 2025, 2014, 2010, 2016, 2002, 2021, 1997, 2020, 2005, 1999, 2023, 2016, 2016, 1957, 2015, 2002, 2014, 1994, 2014, 2002, 2009, 2023, 2006, 2015, 1983, 2013, 2004, 2022, 2009, 2024, 1999, 2019, 1981, 2019, 1979, 1982, 1976, 2022, 1998, 2002, 2008, 1976, 2009, 2020, 2009, 1979, 2025, 1975, 2016, 2024, 2008, 1957, 2011, 1997, 2019, 2001, 2013]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,new,new2
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,1957,1957
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,2017,2017
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,1957,1957
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),2012,2012
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,2011,2011
...,...,...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011,2011,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,1997,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,2019,2019
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,2001,2001
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,2013,2013

In [11]:
df3['added']=df3['Date added']+pd.Timedelta(365,unit='D')
df3

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,new,new2,added
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,1957,1957,1958-03-04
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,2017,2017,2018-07-26
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,1957,1957,1958-03-04
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),2012,2012,2013-12-31
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,2011,2011,2012-07-05
...,...,...,...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011,2011,2011,2012-10-31
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,1997,1997,1998-10-06
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,2019,2019,2020-12-22
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,2001,2001,2002-08-07
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,2013,2013,2014-06-21

In [17]:
df3[df3['Date added'].dt.year>2024]['Symbol'].to_list()

['DASH', 'EXE', 'TKO', 'WSM']