In [ ]:
import numpy as np
import pandas as pd

np1=np.arange(25).reshape(5,5)
df1=pd.DataFrame(np1,index=['r1','r2','r3','r4','r5'],columns=['a','b','c','d','e'])
df1.index.name='r'
df1

In [ ]:
np2=np.arange(100,125).reshape(5,5)
df2=pd.DataFrame(np2,index=['r1','r2','r3','r4','r6'],columns=['c1','c2','c3','c4','c5'])
df2.index.name='r'
df2

In [ ]:
pd.merge(df1,df2,on='r')

In [ ]:
np1=np.arange(25).reshape(5,5)
df1=pd.DataFrame(np1,columns=['r1','r2','r3','r4','r5'],index=['a','b','c','d','e'])
# df1.index.name='r'
print(df1)

np2=np.arange(100,125).reshape(5,5)
df2=pd.DataFrame(np2,columns=['r1','r2','r3','r4','r6'],index=['c1','c2','c3','c4','c5'])
# df2.index.name='r'
print(df2)

In [ ]:
pd.concat([df1,df2],join='outer')

In [ ]:
df1.rename(columns={'r5':'tt','r1':'t5'})

In [ ]:
df1

In [43]:
import pandas as pd
data1=pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')[2]
data2=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]

In [44]:
data1=data1[['Company','Symbol','Industry']]
data1

               Company Symbol                        Industry
0                   3M    MMM                    Conglomerate
1     American Express    AXP              Financial services
2                Amgen   AMGN               Biopharmaceutical
3               Amazon   AMZN                       Retailing
4                Apple   AAPL          Information technology
5               Boeing     BA           Aerospace and defense
6          Caterpillar    CAT         Construction and mining
7              Chevron    CVX              Petroleum industry
8                Cisco   CSCO          Information technology
9            Coca-Cola     KO                  Drink industry
10              Disney    DIS  Broadcasting and entertainment
11       Goldman Sachs     GS              Financial services
12          Home Depot     HD                Home Improvement
13           Honeywell    HON                    Conglomerate
14                 IBM    IBM          Information technology
15   Johnson & Johnson    JNJ         Pharmaceutical industry
16      JPMorgan Chase    JPM              Financial services
17          McDonald's    MCD                   Food industry
18               Merck    MRK         Pharmaceutical industry
19           Microsoft   MSFT          Information technology
20                Nike    NKE               Clothing industry
21              Nvidia   NVDA          Information technology
22    Procter & Gamble     PG      Fast-moving consumer goods
23          Salesforce    CRM          Information technology
24    Sherwin-Williams    SHW             Specialty chemicals
25           Travelers    TRV                       Insurance
26  UnitedHealth Group    UNH             Managed health care
27             Verizon     VZ     Telecommunications industry
28                Visa      V              Financial services
29             Walmart    WMT                       Retailing

In [45]:
# data1=data1[['Company','Symbol','Industry']]
data2=data2.rename(columns={'Company name':'Company','Sector[15]':'Industry'})
data2=data2[['Company','Symbol','Industry']]
data2

,Company,Symbol,Industry
0,Adani Enterprises,ADANIENT,Metals & Mining
1,Adani Ports & SEZ,ADANIPORTS,Services
2,Apollo Hospitals,APOLLOHOSP,Healthcare
3,Asian Paints,ASIANPAINT,Consumer Durables
4,Axis Bank,AXISBANK,Financial Services
5,Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components
6,Bajaj Finance,BAJFINANCE,Financial Services
7,Bajaj Finserv,BAJAJFINSV,Financial Services
8,Bharat Electronics,BEL,Capital Goods
9,Bharti Airtel,BHARTIARTL,Telecommunication
10,Cipla,CIPLA,Healthcare
11,Coal India,COALINDIA,"Oil, Gas & Consumable Fuels"
12,Dr. Reddy's Laboratories,DRREDDY,Healthcare
13,Eicher Motors,EICHERMOT,Automobile and Auto Components
14,Eternal,ETERNAL,Consumer Services
15,Grasim Industries,GRASIM,Construction Materials
16,HCLTech,HCLTECH,Information Technology
17,HDFC Bank,HDFCBANK,Financial Services
18,HDFC Life,HDFCLIFE,Financial Services
19,Hero MotoCorp,HEROMOTOCO,Automobile and Auto Components
20,Hindalco Industries,HINDALCO,Metals & Mining
21,Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods
22,ICICI Bank,ICICIBANK,Financial Services
23,IndusInd Bank,INDUSINDBK,Financial Services
24,Infosys,INFY,Information Technology
25,ITC,ITC,Fast Moving Consumer Goods
26,Jio Financial Services,JIOFIN,Financial Services
27,JSW Steel,JSWSTEEL,Metals & Mining
28,Kotak Mahindra Bank,KOTAKBANK,Financial Services
29,Larsen & Toubro,LT,Construction
30,Mahindra & Mahindra,M&M,Automobile and Auto Components
31,Maruti Suzuki,MARUTI,Automobile and Auto Components
32,Nestlé India,NESTLEIND,Fast Moving Consumer Goods
33,NTPC,NTPC,Power
34,Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels"
35,Power Grid,POWERGRID,Power
36,Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels"
37,SBI Life Insurance Company,SBILIFE,Financial Services
38,Shriram Finance,SHRIRAMFIN,Financial Services
39,State Bank of India,SBIN,Financial Services
40,Sun Pharma,SUNPHARMA,Healthcare
41,Tata Consultancy Services,TCS,Information Technology
42,Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods
43,Tata Motors,TATAMOTORS,Automobile and Auto Components
44,Tata Steel,TATASTEEL,Metals & Mining
45,Tech Mahindra,TECHM,Information Technology
46,Titan Company,TITAN,Consumer Durables
47,Trent,TRENT,Consumer Services
48,UltraTech Cement,ULTRACEMCO,Construction Materials
49,Wipro,WIPRO,Information Technology

In [46]:
pd.concat([data1,data2]).reset_index()

    index           Company      Symbol                Industry
0       0                3M         MMM            Conglomerate
1       1  American Express         AXP      Financial services
2       2             Amgen        AMGN       Biopharmaceutical
3       3            Amazon        AMZN               Retailing
4       4             Apple        AAPL  Information technology
..    ...               ...         ...                     ...
75     45     Tech Mahindra       TECHM  Information Technology
76     46     Titan Company       TITAN       Consumer Durables
77     47             Trent       TRENT       Consumer Services
78     48  UltraTech Cement  ULTRACEMCO  Construction Materials
79     49             Wipro       WIPRO  Information Technology

[80 rows x 4 columns]