In [22]:
import pandas as pd
data1=pd.read_html('https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average')[2]
data1

,Company,Exchange,Symbol,Industry,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,2.11%
1,American Express,NYSE,AXP,Financial services,1982-08-30,NaN,4.37%
2,Amgen,NASDAQ,AMGN,Biopharmaceutical,2020-08-31,NaN,3.89%
3,Amazon,NASDAQ,AMZN,Retailing,2024-02-26,NaN,3.21%
4,Apple,NASDAQ,AAPL,Information technology,2015-03-19,NaN,3.25%
5,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,NaN,2.46%
6,Caterpillar,NYSE,CAT,Construction and mining,1991-05-06,NaN,5.13%
7,Chevron,NYSE,CVX,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.14%
8,Cisco,NASDAQ,CSCO,Information technology,2009-06-08,NaN,0.83%
9,Coca-Cola,NYSE,KO,Drink industry,1987-03-12,Also 1932-05-26 to 1935-11-20,0.88%
10,Disney,NYSE,DIS,Broadcasting and entertainment,1991-05-06,NaN,1.55%
11,Goldman Sachs,NYSE,GS,Financial services,2013-09-23,NaN,8.84%
12,Home Depot,NYSE,HD,Home Improvement,1999-11-01,NaN,5.67%
13,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,AlliedSignal and Honeywell,3.07%
14,IBM,NYSE,IBM,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.54%
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,NaN,2.09%
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,NaN,3.67%
17,McDonald's,NYSE,MCD,Food industry,1985-10-30,NaN,3.97%
18,Merck,NYSE,MRK,Pharmaceutical industry,1979-06-29,NaN,1.35%
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,5.68%
20,Nike,NYSE,NKE,Clothing industry,2013-09-23,NaN,1.07%
21,Nvidia,NASDAQ,NVDA,Information technology,2024-11-08,NaN,1.71%
22,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,NaN,2.29%
23,Salesforce,NYSE,CRM,Information technology,2020-08-31,NaN,4.70%
24,Sherwin-Williams,NYSE,SHW,Specialty chemicals,2024-11-08,NaN,5.00%
25,Travelers,NYSE,TRV,Insurance,2009-06-08,NaN,3.41%
26,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24,NaN,7.47%
27,Verizon,NYSE,VZ,Telecommunications industry,2004-04-08,NaN,0.54%
28,Visa,NYSE,V,Financial services,2013-09-23,NaN,4.70%
29,Walmart,NYSE,WMT,Retailing,1997-03-17,NaN,1.35%

In [23]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          30 non-null     object
 1   Exchange         30 non-null     object
 2   Symbol           30 non-null     object
 3   Industry         30 non-null     object
 4   Date added       30 non-null     object
 5   Notes            5 non-null      object
 6   Index weighting  30 non-null     object
dtypes: object(7)
memory usage: 1.8+ KB

In [4]:
a='1.35%'
float(a.replace('%',''))

1.35

In [11]:
l1=[]
for i in data1['Index weighting']:
    l1.append(float(i.replace('%',"")))
data1['Index weighting']=l1
data1

,Company,Exchange,Symbol,Industry,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,2.11
1,American Express,NYSE,AXP,Financial services,1982-08-30,NaN,4.37
2,Amgen,NASDAQ,AMGN,Biopharmaceutical,2020-08-31,NaN,3.89
3,Amazon,NASDAQ,AMZN,Retailing,2024-02-26,NaN,3.21
4,Apple,NASDAQ,AAPL,Information technology,2015-03-19,NaN,3.25
5,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,NaN,2.46
6,Caterpillar,NYSE,CAT,Construction and mining,1991-05-06,NaN,5.13
7,Chevron,NYSE,CVX,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.14
8,Cisco,NASDAQ,CSCO,Information technology,2009-06-08,NaN,0.83
9,Coca-Cola,NYSE,KO,Drink industry,1987-03-12,Also 1932-05-26 to 1935-11-20,0.88
10,Disney,NYSE,DIS,Broadcasting and entertainment,1991-05-06,NaN,1.55
11,Goldman Sachs,NYSE,GS,Financial services,2013-09-23,NaN,8.84
12,Home Depot,NYSE,HD,Home Improvement,1999-11-01,NaN,5.67
13,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,AlliedSignal and Honeywell,3.07
14,IBM,NYSE,IBM,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.54
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,NaN,2.09
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,NaN,3.67
17,McDonald's,NYSE,MCD,Food industry,1985-10-30,NaN,3.97
18,Merck,NYSE,MRK,Pharmaceutical industry,1979-06-29,NaN,1.35
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,5.68
20,Nike,NYSE,NKE,Clothing industry,2013-09-23,NaN,1.07
21,Nvidia,NASDAQ,NVDA,Information technology,2024-11-08,NaN,1.71
22,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,NaN,2.29
23,Salesforce,NYSE,CRM,Information technology,2020-08-31,NaN,4.70
24,Sherwin-Williams,NYSE,SHW,Specialty chemicals,2024-11-08,NaN,5.00
25,Travelers,NYSE,TRV,Insurance,2009-06-08,NaN,3.41
26,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24,NaN,7.47
27,Verizon,NYSE,VZ,Telecommunications industry,2004-04-08,NaN,0.54
28,Visa,NYSE,V,Financial services,2013-09-23,NaN,4.70
29,Walmart,NYSE,WMT,Retailing,1997-03-17,NaN,1.35

str accessor

In [24]:
data1['Index weighting']=data1['Index weighting'].str.replace('%',"")

In [27]:
data1['Index weighting']=data1['Index weighting'].astype('float')

In [28]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          30 non-null     object
 1   Exchange         30 non-null     object
 2   Symbol           30 non-null     object
 3   Industry         30 non-null     object
 4   Date added       30 non-null     object
 5   Notes            5 non-null      object
 6   Index weighting  30 non-null     float64
dtypes: float64(1), object(6)
memory usage: 1.8+ KB